imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped_main
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        grouped_main:
            type:    group
            members: [nested]

stfalcon_event:
    wayforpay:
        shop_id: "%merchantAccount%"
        secret: "%merchantSecretKey%"
    discount: 0.2

twig:
    globals:
        fb_page_id: "349461782222519"