imports:
    - { resource: config.yml }

sentry:
    skip_capture:
    - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
    dsn: "%sentry_dsn_stag%"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped_main
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        #        sentry:
        #            type:  raven
        #            level: error
        grouped_main:
            type:    group
            members: [nested]

stfalcon_event:
    interkassa:
        shop_id: "%interkassa_shop_id%"
        secret: "%interkassa_secret%"
    discount: 0.2

twig:
    globals:
        fb_page_id: "349461782222519"