imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

behat: ~

mink:
    base_url:   http://fwdays.com.my
#    goutte:     ~   # enable both Goutte
#    sahi:       ~   # and Sahi session
##    sahi:       
##        host:     x.local
#    show_cmd:   google-chrome %%s
#    #default_session: sahi
#    default_session: symfony    
