imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    
framework:
    #esi:             ~
    translator:      { fallback: ru }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
#    form:
#        resources: ['form_table_layout.html.twig']
        
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false
    
# KnpMenuBundle
knp_menu:
    twig: true
    
#avalanche_imagine:
#    filters:
#        events_thumb:
#            type:    thumbnail
#            options: { size: [82, 87], mode: outbound }
#        
#        event_thumb:
#            type:    thumbnail
#            options: { size: [120, 129], mode: outbound }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Application\Bundle\UserBundle\Entity\User
    registration:
        form:
            type: application_user_registration
        confirmation:
            enabled:    true
            template:   FOSUserBundle:Registration:email.txt.twig
    profile:
        form:
            type: application_user_profile
            handler: application_user.profile.form.handler
    from_email:
        address:        orgs@fwdays.com
        sender_name:    Frameworks Days