liip_imagine:
  loaders:
    default:
      filesystem:
        locator: filesystem_insecure
  filter_sets:
    cache: ~
    speaker_size:
      filters:
        relative_resize: { widen: 232, heighten: 232 }
        crop: { size: [ 232, 232 ], start: [ 0, 0 ] }
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }
        optipng: { strip_all: true, level: 5 }
    partner:
      filters:
        downscale:
          max: [280, 150]
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }
        optipng: { strip_all: true, level: 5 }
    upload:
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }
        optipng: { strip_all: true, level: 5 }