StfalconEventBundle:
    resource: "@StfalconEventBundle/Controller/"
    type:     annotation
    prefix:   /

StfalconNewsBundle:
    resource: "@StfalconNewsBundle/Controller/"
    type:     annotation
    prefix:   /

StfalconPageBundle:
    resource: "@StfalconPageBundle/Controller/"
    type:     annotation
    prefix:   /

ApplicationDefaultBundle:
    resource: "@ApplicationDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
_imagine:
    resource: .
    type: imagine
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
