security:
    encoders:
        'Application\Bundle\UserBundle\Entity\User':
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me: true
            remember_me:
                key: %secret%
                lifetime: 31536000 # 365 days in seconds
                path: ~
                domain: ~
                always_remember_me: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_VOLUNTEER:   ROLE_USER
        ROLE_ADMIN:       ROLE_VOLUNTEER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

#    acl:
#        connection: default

jms_security_extra:
    secure_all_services: false
    expressions: true
