services:

    app.ticket_cost.admin:
        class: Application\Bundle\DefaultBundle\Admin\TicketCostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Билеты", label: "Цены событий" }
        arguments: [~, 'Application\Bundle\DefaultBundle\Entity\TicketCost', ~]
