services:

    app.ticket_cost.admin:
        class: Application\Bundle\DefaultBundle\Admin\TicketCostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm}
        arguments: [~, 'Application\Bundle\DefaultBundle\Entity\TicketCost', ~]

    app.twig.extemtion:
        class: Application\Bundle\DefaultBundle\Twig\AppExtension
        tags:
            - { name: twig.extension}

    app.url_for_redirect:
        class: Application\Bundle\DefaultBundle\Service\UrlForRedirect
        arguments: ["@router", "%locales%"]

    app.event.validator:
        class: Application\Bundle\DefaultBundle\Validator\Constraints\Event\EventDateValidator
        tags:
            - { name: validator.constraint_validator, alias: event }
    app.event_ticket_cost.validator:
        class: Application\Bundle\DefaultBundle\Validator\Constraints\Event\EventTicketCostCountValidator
        tags:
            - { name: validator.constraint_validator, alias: event }

    app.ticket_cost.validator:
        class: Application\Bundle\DefaultBundle\Validator\Constraints\TicketCost\TicketCostCountValidator
        tags:
            - { name: validator.constraint_validator, alias: ticketCost }

    app.ticket_cost.service:
        class: Application\Bundle\DefaultBundle\Service\TicketCostService
        arguments: ["@doctrine.orm.entity_manager"]

    stfalcon_event.ticket.service:
        class: Application\Bundle\DefaultBundle\Service\TicketService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%stfalcon_event.config%"
            - "@translator"
            - "@router"
            - "@app.ticket_cost.service"